// Mock / sampling data for /dashboard/balance — untuk demo, laporan, dan testing tanpa harus isi DB manual
// Semua angka sengaja dibuat ada yang BALANCED dan ada yang DEVIATED agar deviasi terlihat jelas di UI & export

export const mockMaterialRows = [
  {
    id: "mock-lot-1",
    lotNumber: "BB-MOCK-001",
    qrCode: "MAT-MOCK001A1B2C",
    skuCode: "KTN-001",
    skuName: "Kain Katun Premium",
    initialQty: 1000,
    quantity: 200,
    usedQty: 800,
    producedQty: 800,
    qcSuccess: 760,
    qcReject: 40,
    qcTotal: 800,
    lotDeviation: 0,
    qcDeviation: 0,
    totalDeviation: 0,
    status: "BALANCED",
    lotStatus: "AVAILABLE",
    createdAt: "2026-08-15T08:00:00.000Z",
  },
  {
    id: "mock-lot-2",
    lotNumber: "BB-MOCK-002",
    qrCode: "MAT-MOCK002D3E4F",
    skuCode: "DRL-002",
    skuName: "Kain Drill Seragam",
    initialQty: 500,
    quantity: 50,
    usedQty: 450,
    producedQty: 430,
    qcSuccess: 400,
    qcReject: 30,
    qcTotal: 430,
    lotDeviation: 20, // 450 - 430 = 20 hilang (waste / belum catat)
    qcDeviation: 0,
    totalDeviation: 20,
    status: "DEVIATED",
    lotStatus: "AVAILABLE",
    createdAt: "2026-08-18T09:30:00.000Z",
  },
  {
    id: "mock-lot-3",
    lotNumber: "BB-MOCK-003",
    qrCode: "MAT-MOCK003G5H6I",
    skuCode: "OXF-003",
    skuName: "Kain Oxford Putih",
    initialQty: 1200,
    quantity: 0,
    usedQty: 1200,
    producedQty: 1200,
    qcSuccess: 1150,
    qcReject: 50,
    qcTotal: 1200,
    lotDeviation: 0,
    qcDeviation: 0,
    totalDeviation: 0,
    status: "BALANCED",
    lotStatus: "EMPTY",
    createdAt: "2026-08-20T10:15:00.000Z",
  },
  {
    id: "mock-lot-4",
    lotNumber: "BB-MOCK-004",
    qrCode: "MAT-MOCK004J7K8L",
    skuCode: "LIN-004",
    skuName: "Kain Linen Cream",
    initialQty: 800,
    quantity: 300,
    usedQty: 500,
    producedQty: 500,
    qcSuccess: 480,
    qcReject: 15,
    qcTotal: 495,
    lotDeviation: 0,
    qcDeviation: 5, // 500 - 495 = 5 belum QC
    totalDeviation: 5,
    status: "DEVIATED",
    lotStatus: "AVAILABLE",
    createdAt: "2026-08-22T13:00:00.000Z",
  },
  {
    id: "mock-lot-5",
    lotNumber: "BB-MOCK-005",
    qrCode: "MAT-MOCK005M9N0O",
    skuCode: "DNM-005",
    skuName: "Kain Denim Indigo",
    initialQty: 600,
    quantity: 100,
    usedQty: 500,
    producedQty: 480,
    qcSuccess: 460,
    qcReject: 20,
    qcTotal: 480,
    lotDeviation: 20,
    qcDeviation: 0,
    totalDeviation: 20,
    status: "DEVIATED",
    lotStatus: "AVAILABLE",
    createdAt: "2026-08-25T07:45:00.000Z",
  },
  {
    id: "mock-lot-6",
    lotNumber: "BB-MOCK-006",
    qrCode: "MAT-MOCK006P1Q2R",
    skuCode: "TWL-006",
    skuName: "Kain Twill Navy",
    initialQty: 1000,
    quantity: 600,
    usedQty: 400,
    producedQty: 400,
    qcSuccess: 380,
    qcReject: 20,
    qcTotal: 400,
    lotDeviation: 0,
    qcDeviation: 0,
    totalDeviation: 0,
    status: "BALANCED",
    lotStatus: "AVAILABLE",
    createdAt: "2026-08-28T11:20:00.000Z",
  },
]

export const mockProductionRows = [
  {
    id: "mock-assign-1",
    joNumber: "JO260901-A1B2",
    lotNumber: "BB-MOCK-001",
    employeeName: "Budi Santoso",
    employeeId: "emp-1",
    jobOrderId: "jo-1",
    materialLotId: "mock-lot-1",
    targetQty: 500,
    completedQty: 480,
    rejectedQty: 20,
    acceptedQty: 480,
    pendingQty: 0,
    progressTotal: 500,
    progressCount: 5,
    status: "COMPLETED",
    assignmentDeviation: 0, // 500 - (480+20)=0
    totalDeviation: 0,
    balanceStatus: "BALANCED",
    hasProgressMismatch: false,
    createdAt: "2026-08-16T08:00:00.000Z",
  },
  {
    id: "mock-assign-2",
    joNumber: "JO260902-B2C3",
    lotNumber: "BB-MOCK-002",
    employeeName: "Siti Aminah",
    employeeId: "emp-2",
    jobOrderId: "jo-2",
    materialLotId: "mock-lot-2",
    targetQty: 400,
    completedQty: 300,
    rejectedQty: 30,
    acceptedQty: 300,
    pendingQty: 70,
    progressTotal: 370,
    progressCount: 4,
    status: "IN_PROGRESS",
    assignmentDeviation: 70, // 400 - 330 =70 belum selesai (tapi IN_PROGRESS jadi tidak dihitung deviasi total)
    totalDeviation: 0, // IN_PROGRESS => 0 di summary
    balanceStatus: "BALANCED",
    hasProgressMismatch: false,
    createdAt: "2026-08-19T09:00:00.000Z",
  },
  {
    id: "mock-assign-3",
    joNumber: "JO260903-C3D4",
    lotNumber: "BB-MOCK-003",
    employeeName: "Agus Pratama",
    employeeId: "emp-3",
    jobOrderId: "jo-3",
    materialLotId: "mock-lot-3",
    targetQty: 300,
    completedQty: 200,
    rejectedQty: 50,
    acceptedQty: 200,
    pendingQty: 0,
    progressTotal: 250,
    progressCount: 3,
    status: "COMPLETED",
    assignmentDeviation: 50, // 300 -250 =50 kurang
    totalDeviation: 50,
    balanceStatus: "DEVIATED",
    hasProgressMismatch: false,
    createdAt: "2026-08-21T10:00:00.000Z",
  },
  {
    id: "mock-assign-4",
    joNumber: "JO260904-D4E5",
    lotNumber: "BB-MOCK-004",
    employeeName: "Rina Wati",
    employeeId: "emp-4",
    jobOrderId: "jo-4",
    materialLotId: "mock-lot-4",
    targetQty: 600,
    completedQty: 550,
    rejectedQty: 50,
    acceptedQty: 550,
    pendingQty: 0,
    progressTotal: 600,
    progressCount: 6,
    status: "COMPLETED",
    assignmentDeviation: 0,
    totalDeviation: 0,
    balanceStatus: "BALANCED",
    hasProgressMismatch: false,
    createdAt: "2026-08-23T14:00:00.000Z",
  },
  {
    id: "mock-assign-5",
    joNumber: "JO260905-E5F6",
    lotNumber: "BB-MOCK-005",
    employeeName: "Joko Widodo",
    employeeId: "emp-5",
    jobOrderId: "jo-5",
    materialLotId: "mock-lot-5",
    targetQty: 250,
    completedQty: 180,
    rejectedQty: 20,
    acceptedQty: 180,
    pendingQty: 30,
    progressTotal: 210,
    progressCount: 2,
    status: "QC_REQUESTED",
    assignmentDeviation: 50,
    totalDeviation: 0,
    balanceStatus: "BALANCED",
    hasProgressMismatch: true, // progress 210 vs pending+completed 210? sengaja mismatch demo
    createdAt: "2026-08-26T08:30:00.000Z",
  },
  {
    id: "mock-assign-6",
    joNumber: "JO260906-F6G7",
    lotNumber: "BB-MOCK-006",
    employeeName: "Dewi Lestari",
    employeeId: "emp-6",
    jobOrderId: "jo-6",
    materialLotId: "mock-lot-6",
    targetQty: 800,
    completedQty: 800,
    rejectedQty: 0,
    acceptedQty: 800,
    pendingQty: 0,
    progressTotal: 800,
    progressCount: 8,
    status: "COMPLETED",
    assignmentDeviation: 0,
    totalDeviation: 0,
    balanceStatus: "BALANCED",
    hasProgressMismatch: false,
    createdAt: "2026-08-29T09:15:00.000Z",
  },
]

export const mockStockRows = [
  {
    id: "mock-stock-1",
    productId: "prod-1",
    productSku: "KPDL-H-M",
    productName: "Kemeja PDL Hitam - M",
    warehouseId: "wh-1",
    warehouseName: "Gudang Utama",
    warehouseCode: "GD-UTM",
    systemQty: 500,
    computedQty: 500,
    reservedQty: 0,
    deviation: 0,
    absDeviation: 0,
    status: "BALANCED",
    updatedAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "mock-stock-2",
    productId: "prod-2",
    productSku: "CPDL-H-L",
    productName: "Celana PDL Hitam - L",
    warehouseId: "wh-1",
    warehouseName: "Gudang Utama",
    warehouseCode: "GD-UTM",
    systemQty: 300,
    computedQty: 295,
    reservedQty: 0,
    deviation: 5,
    absDeviation: 5,
    status: "DEVIATED",
    updatedAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "mock-stock-3",
    productId: "prod-3",
    productSku: "KAOS-P-U",
    productName: "Kaos Polo Uniform",
    warehouseId: "wh-2",
    warehouseName: "Gudang Bahan Jadi",
    warehouseCode: "GD-BJD",
    systemQty: 800,
    computedQty: 800,
    reservedQty: 0,
    deviation: 0,
    absDeviation: 0,
    status: "BALANCED",
    updatedAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "mock-stock-4",
    productId: "prod-4",
    productSku: "JKT-H-M",
    productName: "Jaket Lapangan Hitam - M",
    warehouseId: "wh-3",
    warehouseName: "Gudang Reject",
    warehouseCode: "GD-RJC",
    systemQty: 120,
    computedQty: 118,
    reservedQty: 0,
    deviation: 2,
    absDeviation: 2,
    status: "DEVIATED",
    updatedAt: "2026-09-01T10:00:00.000Z",
  },
  {
    id: "mock-stock-5",
    productId: "prod-5",
    productSku: "TOPI-H",
    productName: "Topi PDL Hitam",
    warehouseId: "wh-2",
    warehouseName: "Gudang Bahan Jadi",
    warehouseCode: "GD-BJD",
    systemQty: 0,
    computedQty: 45,
    reservedQty: 0,
    deviation: -45,
    absDeviation: 45,
    status: "ORPHAN",
    updatedAt: null as unknown as string,
  },
]

export const mockSummary = {
  material: {
    initial: 5100,
    remaining: 1150,
    used: 3950,
    produced: 3810,
    deviation: 45, // |3950-3810| + qc dev etc = total beau
    status: "DEVIATED" as const,
    lotsCount: 6,
  },
  production: {
    target: 2850,
    completed: 2510,
    rejected: 170,
    accepted: 2510,
    pending: 100,
    progress: 2730,
    deviation: 50,
    status: "DEVIATED" as const,
    assignmentsCount: 6,
  },
  qc: {
    success: 3840,
    reject: 175,
    total: 4015,
    deviation: 205, // 3810 vs 4015? sengaja demo: produksi 3810 belum semua QC
    status: "DEVIATED" as const,
    reportsCount: 6,
  },
  stock: {
    system: 1720,
    computed: 1758,
    deviation: -38,
    status: "DEVIATED" as const,
    stockRows: 5,
    movementsCount: 42,
  },
  transfer: {
    totalQty: 1250,
    pending: 2,
    completed: 8,
    total: 10,
    itemsCount: 18,
  },
  overall: {
    totalDeviation: 133, // 45+50+38
    isBalanced: false,
    deviatedModules: ["MATERIAL", "PRODUCTION", "STOCK", "QC"] as string[],
  },
}

export const mockMaterialSummary = {
  total: mockMaterialRows.length,
  balanced: mockMaterialRows.filter(r => r.status === "BALANCED").length,
  deviated: mockMaterialRows.filter(r => r.status === "DEVIATED").length,
  totalDeviation: mockMaterialRows.reduce((s, r) => s + Math.abs(r.totalDeviation), 0),
}

export const mockProductionSummary = {
  total: mockProductionRows.length,
  balanced: mockProductionRows.filter(r => r.balanceStatus === "BALANCED").length,
  deviated: mockProductionRows.filter(r => r.balanceStatus === "DEVIATED").length,
  totalDeviation: mockProductionRows.reduce((s, r) => s + Math.abs(r.totalDeviation), 0),
  totalTarget: mockProductionRows.reduce((s, r) => s + r.targetQty, 0),
  totalCompleted: mockProductionRows.reduce((s, r) => s + r.completedQty, 0),
  totalRejected: mockProductionRows.reduce((s, r) => s + r.rejectedQty, 0),
  totalPending: mockProductionRows.reduce((s, r) => s + r.pendingQty, 0),
}

export const mockStockSummary = {
  total: mockStockRows.length,
  balanced: mockStockRows.filter(r => r.status === "BALANCED").length,
  deviated: mockStockRows.filter(r => r.status === "DEVIATED").length,
  orphan: mockStockRows.filter(r => r.status === "ORPHAN").length,
  totalDeviation: mockStockRows.reduce((s, r) => s + Math.abs(r.deviation), 0),
  totalSystemQty: mockStockRows.reduce((s, r) => s + r.systemQty, 0),
  totalComputedQty: mockStockRows.reduce((s, r) => s + r.computedQty, 0),
}
